[package]
name = "sc-deainostri-nft-staking-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.sc-deainostri-nft-staking]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.32.0"
